# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/vll/baixadorvideo/tela.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_o(object):
    def setupUi(self, o):
        o.setObjectName("o")
        o.resize(504, 298)
        self.centralWidget = QtWidgets.QWidget(o)
        self.centralWidget.setObjectName("centralWidget")
        self.pushButton = QtWidgets.QPushButton(self.centralWidget)
        self.pushButton.setGeometry(QtCore.QRect(180, 150, 151, 31))
        self.pushButton.setObjectName("pushButton")
        self.lineEdit = QtWidgets.QLineEdit(self.centralWidget)
        self.lineEdit.setGeometry(QtCore.QRect(30, 70, 441, 31))
        self.lineEdit.setObjectName("lineEdit")
        self.label = QtWidgets.QLabel(self.centralWidget)
        self.label.setGeometry(QtCore.QRect(150, 10, 211, 41))
        self.label.setStyleSheet("font: 14pt \"DejaVu Sans\";\n"
"background-color: rgb(255, 255, 0);")
        self.label.setObjectName("label")
        o.setCentralWidget(self.centralWidget)
        self.menuBar = QtWidgets.QMenuBar(o)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 504, 20))
        self.menuBar.setObjectName("menuBar")
        o.setMenuBar(self.menuBar)
        self.mainToolBar = QtWidgets.QToolBar(o)
        self.mainToolBar.setObjectName("mainToolBar")
        o.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtWidgets.QStatusBar(o)
        self.statusBar.setObjectName("statusBar")
        o.setStatusBar(self.statusBar)

        self.retranslateUi(o)
        QtCore.QMetaObject.connectSlotsByName(o)

    def retranslateUi(self, o):
        _translate = QtCore.QCoreApplication.translate
        o.setWindowTitle(_translate("o", "Baixar do Youtube"))
        self.pushButton.setText(_translate("o", "Baixar"))
        self.label.setText(_translate("o", "<html><head/><body><p align=\"center\">Digite o Link</p></body></html>"))
